In [10]:
import sklearn
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [62]:
data = pd.read_csv("/content/drive/MyDrive/dataset/Iris.csv")

In [59]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  139 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


**Encoding**

In [60]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
df = data
df['Species'].value_counts()
lenc = LabelEncoder()
df['Species'] = lenc.fit_transform(df['Species'])
print(df['Species'].value_counts())
lenc.classes_

2    50
1    50
0    50
Name: Species, dtype: int64


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [63]:
data['Species'].value_counts()

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: Species, dtype: int64

In [64]:
one_hot = OneHotEncoder()
transformed_data = one_hot.fit_transform(data['Species'].values.reshape(-1,1)).toarray()
one_hot.categories_

[array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)]

In [65]:
transformed_data = pd.DataFrame(transformed_data , 
                                columns = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

In [66]:
transformed_data.head() 

Iris-setosa  Iris-versicolor  Iris-virginica
0          1.0              0.0             0.0
1          1.0              0.0             0.0
2          1.0              0.0             0.0
3          1.0              0.0             0.0
4          1.0              0.0             0.0

In [71]:
transformed_data.iloc[100 , ]

Iris-setosa        0.0
Iris-versicolor    0.0
Iris-virginica     1.0
Name: 100, dtype: float64

In [72]:
data['Species'][100]

'Iris-virginica'

**Handling With Missing Values**

In [51]:
data.isnull().sum()

Id                0
SepalLengthCm    11
SepalWidthCm      0
PetalLengthCm     0
PetalWidthCm      0
Species           0
dtype: int64

In [52]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')
SepalLengthCm = imputer.fit_transform(df['SepalLengthCm'].values.reshape(-1,1))
print(pd.DataFrame(SepalLengthCm).isnull().sum())
df['SepalLengthCm'] = pd.DataFrame(SepalLengthCm)

0    0
dtype: int64


**Sklearn Preprocessing**

In [53]:
x = df.iloc[:,1]
y_scaled = preprocessing.scale(x)
print(y_scaled)

[-0.88165977 -1.12873781 -1.37581586 -1.49935488 -1.00519879 -0.51104271
 -1.49935488 -1.00519879 -1.74643292 -1.12873781 -0.51104271 -1.25227684
 -1.25227684 -1.86997194 -0.01688663 -0.14042565 -0.51104271 -0.88165977
 -0.14042565 -0.88165977 -0.51104271 -0.88165977 -1.49935488 -0.88165977
 -1.25227684 -1.00519879 -1.00519879 -0.75812075 -0.75812075 -1.37581586
 -1.25227684 -0.51104271 -0.75812075 -0.38750369 -1.12873781 -1.00519879
 -0.38750369 -1.12873781 -1.74643292 -0.88165977 -1.00519879 -1.6228939
 -1.74643292 -1.00519879 -0.88165977 -1.25227684 -0.88165977 -1.49935488
 -0.63458173 -1.00519879  0.          0.          0.         -0.38750369
  0.84788652 -0.14042565  0.60080847 -1.12873781  0.97142554 -0.75812075
 -1.00519879  0.10665239  0.23019141  0.35373043 -0.26396467  1.09496456
 -0.26396467 -0.01688663  0.47726945 -0.26396467  0.10665239  0.35373043
  0.60080847  0.35373043  0.7243475   0.97142554  1.21850358  1.09496456
  0.23019141 -0.14042565 -0.38750369 -0.38750369 -0.

In [54]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
x = df.iloc[:,1:4]
scaler = MinMaxScaler(feature_range=(0,5))
scaler.fit(x)
new_data = scaler.transform(x)
new_data

array([[1.11111111, 3.125     , 0.33898305],
       [0.83333333, 2.08333333, 0.33898305],
       [0.55555556, 2.5       , 0.25423729],
       [0.41666667, 2.29166667, 0.42372881],
       [0.97222222, 3.33333333, 0.33898305],
       [1.52777778, 3.95833333, 0.59322034],
       [0.41666667, 2.91666667, 0.33898305],
       [0.97222222, 2.91666667, 0.42372881],
       [0.13888889, 1.875     , 0.33898305],
       [0.83333333, 2.29166667, 0.42372881],
       [1.52777778, 3.54166667, 0.42372881],
       [0.69444444, 2.91666667, 0.50847458],
       [0.69444444, 2.08333333, 0.33898305],
       [0.        , 2.08333333, 0.08474576],
       [2.08333333, 4.16666667, 0.16949153],
       [1.94444444, 5.        , 0.42372881],
       [1.52777778, 3.95833333, 0.25423729],
       [1.11111111, 3.125     , 0.33898305],
       [1.94444444, 3.75      , 0.59322034],
       [1.11111111, 3.75      , 0.42372881],
       [1.52777778, 2.91666667, 0.59322034],
       [1.11111111, 3.54166667, 0.42372881],
       [0.

In [74]:
from sklearn.preprocessing import KBinsDiscretizer
trans = KBinsDiscretizer(n_bins=2, encode = 'ordinal',strategy='quantile')
new_data = trans.fit_transform(x)
new_data

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [75]:
trans = KBinsDiscretizer(n_bins=2, encode = 'ordinal',strategy='kmeans')
new_data = trans.fit_transform(x)
new_data

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0